"""以短信复制为中心的简洁主界面。"""
from PySide6.QtCore import Qt
from PySide6.QtGui import QKeySequence, QShortcut
from PySide6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QLabel, QLineEdit, QPushButton,
    QSpinBox, QCheckBox, QSplitter, QTableWidget, QAbstractItemView, QHeaderView,
    QPlainTextEdit, QFormLayout, QTabWidget, QFrame)


def build_main_ui(w, config):
    w.setWindowTitle('宣讲会信息助手')
    w.resize(1140, 780)
    w.setMinimumSize(940, 650)
    central = QWidget()
    w.setCentralWidget(central)
    root = QVBoxLayout(central)
    root.setContentsMargins(20, 18, 20, 12)
    root.setSpacing(12)
    title = QLabel('宣讲会信息助手')
    title.setObjectName('title')
    root.addWidget(title)
    file_row = QHBoxLayout()
    w.path_edit = QLineEdit(config['last_path'])
    w.path_edit.setPlaceholderText('选择每周宣讲会 Excel 名单')
    w.choose_btn = QPushButton('选择 Excel')
    w.choose_btn.clicked.connect(w.choose_file)
    w.read_btn = QPushButton('读取名单')
    w.read_btn.clicked.connect(w.start_read)
    file_row.addWidget(w.path_edit, 1)
    file_row.addWidget(w.choose_btn)
    file_row.addWidget(QLabel('筛选姓名'))
    w.name_edit = QLineEdit(config['name'])
    w.name_edit.setMaximumWidth(100)
    file_row.addWidget(w.name_edit)
    file_row.addWidget(w.read_btn)
    root.addLayout(file_row)
    summary = QHBoxLayout()
    w.stats = QLabel('选择名单后点击“读取名单”，即可复制短信。')
    w.stats.setTextFormat(Qt.PlainText)
    w.stats.setWordWrap(True)
    summary.addWidget(w.stats, 1)
    w.options_btn = QPushButton('设置与导出')
    w.options_btn.setCheckable(True)
    summary.addWidget(w.options_btn)
    root.addLayout(summary)
    w.options_panel = QWidget()
    settings = QHBoxLayout(w.options_panel)
    settings.setContentsMargins(0, 0, 0, 0)
    settings.addWidget(QLabel('默认时长'))
    w.duration = QSpinBox()
    w.duration.setRange(1, 1440)
    w.duration.setValue(config['duration'])
    w.duration.setSuffix(' 分钟')
    settings.addWidget(w.duration)
    w.remember = QCheckBox('记住文件路径')
    w.remember.setChecked(config['remember_path'])
    settings.addWidget(w.remember)
    settings.addStretch()
    w.reload_btn = QPushButton('重新读取')
    w.reload_btn.clicked.connect(w.start_read)
    w.layout_btn = QPushButton('列设置 / 原表预览')
    w.layout_btn.clicked.connect(w.configure_columns)
    w.layout_btn.setEnabled(False)
    w.export_btn = QPushButton('导出 Excel')
    w.export_btn.clicked.connect(w.export)
    w.export_btn.setEnabled(False)
    for button in (w.reload_btn, w.layout_btn, w.export_btn):
        settings.addWidget(button)
    root.addWidget(w.options_panel)
    w.options_panel.hide()
    w.options_btn.toggled.connect(w.options_panel.setVisible)
    w.warnings = QPlainTextEdit()
    w.warnings.setReadOnly(True)
    w.warnings.setMaximumHeight(74)
    w.warnings.setStyleSheet('color:#b42318; background:#fff5f3;')
    w.warnings.hide()
    root.addWidget(w.warnings)
    splitter = QSplitter(Qt.Horizontal)
    root.addWidget(splitter, 1)
    left = QWidget()
    left_layout = QVBoxLayout(left)
    left_layout.setContentsMargins(0, 0, 8, 0)
    w.search = QLineEdit()
    w.search.setPlaceholderText('搜索企业 / 手机号')
    w.search.textChanged.connect(w.refresh_list)
    left_layout.addWidget(w.search)
    w.table = QTableWidget(0, 3)
    w.table.setHorizontalHeaderLabels(['企业', '时间', '教室'])
    w.table.setSelectionBehavior(QAbstractItemView.SelectRows)
    w.table.setSelectionMode(QAbstractItemView.SingleSelection)
    w.table.setEditTriggers(QAbstractItemView.NoEditTriggers)
    w.table.verticalHeader().hide()
    w.table.setWordWrap(False)
    w.table.setAlternatingRowColors(True)
    w.table.setShowGrid(False)
    w.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
    w.table.setColumnWidth(1, 117)
    w.table.setColumnWidth(2, 70)
    w.table.itemSelectionChanged.connect(w.show_record)
    left_layout.addWidget(w.table)
    w.list_count = QLabel('0 条记录')
    left_layout.addWidget(w.list_count)
    splitter.addWidget(left)
    w.tabs = QTabWidget()
    splitter.addWidget(w.tabs)
    page = QWidget()
    detail = QVBoxLayout(page)
    detail.setContentsMargins(16, 16, 16, 12)
    detail.setSpacing(10)
    w.company = QLabel('请选择一家企业')
    w.company.setTextFormat(Qt.PlainText)
    w.company.setWordWrap(True)
    detail.addWidget(w.company)
    w.record_status = QLabel()
    w.record_status.setTextFormat(Qt.PlainText)
    w.record_status.setWordWrap(True)
    detail.addWidget(w.record_status)
    w.contact, w.phone, w.time, w.address, w.source = [QLabel('—') for _ in range(5)]
    for label in (w.contact, w.phone, w.time, w.address, w.source):
        label.setTextFormat(Qt.PlainText)
        label.setWordWrap(True)
        label.setTextInteractionFlags(Qt.TextSelectableByMouse)
    detail.addWidget(w.time)
    detail.addWidget(w.address)
    phone_row = QHBoxLayout()
    phone_row.addWidget(w.phone, 1)
    w.copy_phone = QPushButton('复制手机号')
    w.copy_phone.clicked.connect(w.copy_number)
    phone_row.addWidget(w.copy_phone)
    detail.addLayout(phone_row)
    w.message = QPlainTextEdit()
    w.message.setReadOnly(True)
    w.message.setMinimumHeight(170)
    w.message.setPlaceholderText('固定短信正文会显示在这里')
    detail.addWidget(w.message, 1)
    w.copy_message = QPushButton('复制短信')
    w.copy_message.setObjectName('primary')
    w.copy_message.setMinimumHeight(44)
    w.copy_message.clicked.connect(w.copy_sms)
    detail.addWidget(w.copy_message)
    nav = QHBoxLayout()
    w.previous, w.next = QPushButton('上一家'), QPushButton('下一家')
    w.position = QLabel('0 / 0')
    w.position.setAlignment(Qt.AlignCenter)
    w.previous.clicked.connect(lambda: w.move(-1))
    w.next.clicked.connect(lambda: w.move(1))
    nav.addWidget(w.previous)
    nav.addWidget(w.position, 1)
    nav.addWidget(w.next)
    detail.addLayout(nav)
    w.details_btn = QPushButton('联系人与来源')
    w.details_btn.setCheckable(True)
    detail.addWidget(w.details_btn)
    w.details_panel = QWidget()
    form = QFormLayout(w.details_panel)
    form.setContentsMargins(0, 0, 0, 0)
    form.addRow('联系人', w.contact)
    form.addRow('来源', w.source)
    w.copy_all = QPushButton('复制全部信息')
    w.copy_all.clicked.connect(w.copy_details)
    form.addRow(w.copy_all)
    detail.addWidget(w.details_panel)
    w.details_panel.hide()
    w.details_btn.toggled.connect(w.details_panel.setVisible)
    w.tabs.addTab(page, '短信复制')
    plan = QWidget()
    plan_layout = QVBoxLayout(plan)
    plan_layout.setContentsMargins(16, 16, 16, 16)
    note = QLabel('汇总本次读取的全部记录，可复制到手机查看。\n格式：16号 18.40 a103 [手机号] 示例企业')
    note.setWordWrap(True)
    plan_layout.addWidget(note)
    w.sort_schedule = QCheckBox('按日期、时间排序（默认保留 Excel 顺序）')
    w.sort_schedule.toggled.connect(w.refresh_schedule)
    plan_layout.addWidget(w.sort_schedule)
    w.schedule_summary = QLabel('读取名单后自动生成；不受左侧搜索影响。')
    w.schedule_summary.setWordWrap(True)
    plan_layout.addWidget(w.schedule_summary)
    w.schedule_text = QPlainTextEdit()
    w.schedule_text.setReadOnly(True)
    w.schedule_text.setPlaceholderText('接待清单会显示在这里')
    plan_layout.addWidget(w.schedule_text, 1)
    w.copy_schedule = QPushButton('复制接待清单')
    w.copy_schedule.setObjectName('primary')
    w.copy_schedule.setMinimumHeight(44)
    w.copy_schedule.setEnabled(False)
    w.copy_schedule.clicked.connect(w.copy_schedule_text)
    plan_layout.addWidget(w.copy_schedule)
    w.tabs.addTab(plan, '接待清单')
    splitter.setSizes([420, 680])
    w.shortcuts = []
    for key, offset in (('Alt+Left', -1), ('Alt+Right', 1)):
        shortcut = QShortcut(QKeySequence(key), w)
        shortcut.activated.connect(lambda offset=offset: w.move(offset))
        w.shortcuts.append(shortcut)
    w.setStyleSheet('''
        QMainWindow {background:#f5f7fa;}
        QLabel#title {font-size:22px; font-weight:600; color:#1e293b;}
        QPushButton {padding:7px 13px; border:1px solid #cbd5e1; border-radius:5px; background:white;}
        QPushButton:hover {background:#edf3fb;}
        QPushButton:disabled {color:#a1a9b4; background:#f2f4f6;}
        QPushButton#primary {background:#2563a6; color:white; border:0; font-size:16px; font-weight:600;}
        QPushButton#primary:hover {background:#1d518c;}
        QPushButton#primary:disabled {background:#a5b8ce;}
        QLineEdit, QSpinBox {padding:6px; border:1px solid #cbd5e1; border-radius:4px; background:white;}
        QPlainTextEdit {border:1px solid #d8e0ea; border-radius:4px; padding:8px; background:white;}
        QTableWidget {border:1px solid #d8e0ea; background:white; selection-background-color:#dceafb; selection-color:#102c4c;}
        QHeaderView::section {padding:8px; background:#eaf0f6; border:0;}
        QTabWidget::pane {border:1px solid #d8e0ea; background:white;}
        QTabBar::tab {padding:10px 24px; background:#e8edf3;}
        QTabBar::tab:selected {background:white; color:#185591;}
    ''')
    w.statusBar().showMessage('就绪')
    w.show_record()
